### ISSUE TITLE
Tekton tree unable to load some PipelineRun's

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/intellij-tekton#120] opened 2020-06-02 12:56 UTC
When I connect to my CRC cluster I got `Failed to load pipeline runs` when I expand pipeline:
<img width="488" alt="Screenshot 2020-06-02 at 15 47 54" src="https://user-images.githubusercontent.com/929743/83522053-c56f6000-a4e8-11ea-91bd-8a643979ccb0.png">

Same tree in vscode:
<img width="391" alt="Screenshot 2020-06-02 at 15 48 12" src="https://user-images.githubusercontent.com/929743/83522079-cf915e80-a4e8-11ea-8019-b41e4e6ed5c8.png">

I do some investigation, there are exception:
```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[2])
``` 
catched  there: https://github.com/redhat-developer/intellij-tekton/blob/40338f40f32fac05c65c23753ea85cfa493ed4db/src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java#L270
It seems error related to JSON deserialization for `PipelineRun` object

**Comment by lstocchi** [comment] 2020-06-02 17:25
Good catch @evidolob :+1: Is it due to the failing pipeline runs? Why are they failing? Can you give me some info how to replicate this? Thank you :)

**Comment by evidolob** [comment] 2020-06-03 07:38
I use this https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml Pipeline, and have multiple pipelineruns of it. One of them is canceled, not failed.
It is strange when I restart Intellij, pipelinerun for `build-and-deploy` is showing normally(and yes all of them is failed doe to some internal errors related to publishing images)

**Comment by lstocchi** [comment] 2020-06-03 10:49
Ok i was able to reproduce it. The problem is that we currently use `tkn` to find pipelineruns for a pipeline and they don't show pr that never started. 

An example below.
![image](https://user-images.githubusercontent.com/49404737/83628209-6b2dd800-a598-11ea-8952-2145c86cf140.png)

I'll open an issue on the tekton repo to see what they say otherwise we should use fabric8 tekton

**Comment by lstocchi** [comment] 2020-06-08 10:23
Forgot to add the opened issue in tekton cli repo https://github.com/tektoncd/cli/issues/1007

**Comment by lstocchi** [comment] 2021-08-19 10:51
Closing it as i'm not able to replicate it. I guess it was fixed somehow in the last year. Feel free to reopen it if you face it again. :+1:

**Closed by lstocchi** 2021-08-19 10:51 UTC
